### ISSUE TITLE
Hello, I cannot open the projects, the file path cannot be found.

### ISSUE THREAD

**Issue by cryspawner** [singhhdev/cs2-internal-skin-changer#2]
Hello, I cannot open the projects, the file path cannot be found.

**Comment by singhhdev** [comment]
try to open the [cs2cheat.vcxproj.user](https://github.com/singhhdev/cs2-internal-skin-changer/blob/main/cs2cheat.vcxproj.user) file. make sure you also extract the .rar files since i cant upload >100 files on github!

**Comment by Mespeet** [comment]
Just opening cs2cheat.vcxproj.user does absolutely nothing.....

**Comment by cryspawner** [comment]
C:\Users\hasan\Downloads\cs2-internal-skin-changer-main\cs2-internal-skin-changer-main\cs2cheat\dependencies\freetype-2.13.0\builds\windows\vc2010\freetype.vcxproj : error  : Proje dosyası yüklenemedi. 'C:\Users\hasan\Downloads\cs2-internal-skin-changer-main\cs2-internal-skin-changer-main\cs2cheat\dependencies\freetype-2.13.0\builds\windows\vc2010\freetype.vcxproj' yolunun bir parçası bulunamadı.  C:\Users\hasan\Downloads\cs2-internal-skin-changer-main\cs2-internal-skin-changer-main\cs2cheat\dependencies\freetype-2.13.0\builds\windows\vc2010\freetype.vcxproj


C:\Users\hasan\Downloads\cs2-internal-skin-changer-main\cs2-internal-skin-changer-main\cs2cheat\dependencies\freetype-2.13.0\builds\windows\vc2010\freetype.vcxproj : error  : Proje dosyası yüklenemedi. 'C:\Users\hasan\Downloads\cs2-internal-skin-changer-main\cs2-internal-skin-changer-main\cs2cheat\dependencies\freetype-2.13.0\builds\windows\vc2010\freetype.vcxproj' yolunun bir parçası bulunamadı.  C:\Users\hasan\Downloads\cs2-internal-skin-changer-main\cs2-internal-skin-changer-main\cs2cheat\dependencies\freetype-2.13.0\builds\windows\vc2010\freetype.vcxproj

**Comment by Sinnisterly** [comment]
The owner of the repo is missing \cs2-internal-skin-changer-main\cs2cheat\cs2cheat.vcxproj  . The other error freetype.vcxproj can be fixed by removing it from the solution manager (right click freetype and select remove) (https://prnt.sc/cyP3dP_1lQzK) and then right click your project and select Add>Existing Project> go to \cs2-internal-skin-changer-main\dependencies\freetype-2.13.0\builds\windows\vc2010 and add the .vcxproj file for freetype from there. but the other file is completely missing from the github. It is unbuildable without it.

**Comment by singhhdev** [comment]
The Game had an update, i need to fix the .dll again. will post the update in about an hour.

**Comment by cryspawner** [comment]
okey i'm waiting.

**Comment by Mespeet** [comment]
What has happened to the hour? Not complaining but waiting 😄

**Comment by singhhdev** [comment]
updated fixed the knife animations and skin applying on bomb on t side
